### ISSUE TITLE
LamdaでPuppeteerが動かないエラー

### ISSUE THREAD

**Issue by ikemura23** [ikemura23/yaimafuni-batch#70]
エラーログ
```
START RequestId: 16061400-2eec-4bdf-ae85-d4649ef48276 Version: $LATEST
2024-11-08T23:29:55.668Z	16061400-2eec-4bdf-ae85-d4649ef48276	INFO	main init
2024-11-08T23:29:56.082Z	16061400-2eec-4bdf-ae85-d4649ef48276	INFO	main start
2024-11-08T23:29:56.083Z	16061400-2eec-4bdf-ae85-d4649ef48276	INFO	updateAnneiList start
2024-11-08T23:29:56.083Z	16061400-2eec-4bdf-ae85-d4649ef48276	INFO	getAnneiUpdateTimeAndComment start
2024-11-08T23:29:56.083Z	16061400-2eec-4bdf-ae85-d4649ef48276	INFO	await createBrowser()
2024-11-08T23:29:58.177Z	16061400-2eec-4bdf-ae85-d4649ef48276	INFO	await browserFactory.create() end
2024-11-08T23:29:58.178Z	16061400-2eec-4bdf-ae85-d4649ef48276	INFO	try start
2024-11-08T23:29:58.246Z	16061400-2eec-4bdf-ae85-d4649ef48276	INFO	browser.newPage() ok
2024-11-08T23:29:58.360Z	16061400-2eec-4bdf-ae85-d4649ef48276	ERROR	Error getAnneiUpdateTimeAndComment:  ProtocolError: Protocol error (Page.navigate): Target closed.
    at /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)
    at navigate (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:229:47)
    at Frame.goto (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:207:13)
    at CDPPage.goto (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:439:91)
    at getAnneiUpdateTimeAndComment (/var/task/src/list/getAnneiUpdateTimeAndComment.js:17:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateAnneiList (/var/task/src/list/updateAnneiList.js:7:34)
    at async exports.handler (/var/task/index.js:35:5)
2024-11-08T23:29:58.378Z	16061400-2eec-4bdf-ae85-d4649ef48276	INFO	getAnneiList start
2024-11-08T23:29:58.599Z	16061400-2eec-4bdf-ae85-d4649ef48276	INFO	Post to Slack:  ProtocolError: Protocol error (Page.navigate): Target closed.
2024-11-08T23:29:58.638Z	16061400-2eec-4bdf-ae85-d4649ef48276	INFO	Error happended:  TypeError: Cannot read properties of undefined (reading 'updateTime')
    at updateAnneiList (/var/task/src/list/updateAnneiList.js:10:42)
    at async exports.handler (/var/task/index.js:35:5)
END RequestId: 16061400-2eec-4bdf-ae85-d4649ef48276
REPORT RequestId: 16061400-2eec-4bdf-ae85-d4649ef48276	Duration: 3331.57 ms	Billed Duration: 3332 ms	Memory Size: 2048 MB	Max Memory Used: 516 MB	Init Duration: 189.17 ms	
```

**Comment by ikemura23** [comment]
## 参考になりそうなサイト

自分と似た環境
- [API Gateway + Lambda + Puppeteer で任意の Web ページのスクリーンショットを撮って S3 に保存する #Node.js - Qiita](https://qiita.com/takano-h/items/947392a7b697e123cea4) https://qiita.com/takano-h/items/947392a7b697e123cea4

puppeteer-chromium-resolver というライブラリでchromiumのパスを自動解決してくれるらし、気になる
- [PuppeteerとCloud Functons for Firebaseでスクレイピング](https://zenn.dev/takamoso/articles/puppeteer-firebase-cloud-functions) https://zenn.dev/takamoso/articles/puppeteer-firebase-cloud-functions

**Comment by ikemura23** [comment]
無事に対応できて、CloudWatchでも正常に動いてそうなログが確認できた
